// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDukyfz-7SCqUVefq8DXZr5fVI3akMun68',
    appId: '1:829889643695:web:d291b27cc5c3b04013005a',
    messagingSenderId: '829889643695',
    projectId: 'mapsapp-66de9',
    authDomain: 'mapsapp-66de9.firebaseapp.com',
    storageBucket: 'mapsapp-66de9.appspot.com',
    measurementId: 'G-R8EJSLF5J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYIUKBKOQleiBUTOr-Ejt6Kb_Zt42rIyI',
    appId: '1:829889643695:android:fb804e6379a4ca7f13005a',
    messagingSenderId: '829889643695',
    projectId: 'mapsapp-66de9',
    storageBucket: 'mapsapp-66de9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAElpZa5SMqatIkTP6mi59MKZWmhON_ahA',
    appId: '1:829889643695:ios:4d73f4a61a275aaf13005a',
    messagingSenderId: '829889643695',
    projectId: 'mapsapp-66de9',
    storageBucket: 'mapsapp-66de9.appspot.com',
    iosBundleId: 'com.example.mapsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAElpZa5SMqatIkTP6mi59MKZWmhON_ahA',
    appId: '1:829889643695:ios:4d73f4a61a275aaf13005a',
    messagingSenderId: '829889643695',
    projectId: 'mapsapp-66de9',
    storageBucket: 'mapsapp-66de9.appspot.com',
    iosBundleId: 'com.example.mapsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDukyfz-7SCqUVefq8DXZr5fVI3akMun68',
    appId: '1:829889643695:web:374e0fc30e4c3b4c13005a',
    messagingSenderId: '829889643695',
    projectId: 'mapsapp-66de9',
    authDomain: 'mapsapp-66de9.firebaseapp.com',
    storageBucket: 'mapsapp-66de9.appspot.com',
    measurementId: 'G-6KMQETRBDV',
  );
}
